version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    restart: always  
    environment:
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_PUBLIC_CMS_URL: ${PUBLIC_CMS_URL}
      PAYLOAD_PUBLIC_APP_URL: ${PUBLIC_APP_URL}
      PAYLOAD_PUBLIC_DRAFT_SECRET: ${PUBLIC_DRAFT_SECRET}
      REVALIDATION_KEY: ${REVALIDATION_KEY}
      DATABASE_URI: ${DATABASE_URI}
      PAYLOAD_CONFIG_PATH: dist/payload.config.js
      PORT: 7500
      NODE_ENV: production
    volumes:
      - payload:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn build && yarn serve"
    # command: sh -c "npm install pm2 -g && pm2 start /root/home/node/app/ecosystem.config.js --env production"
    depends_on:
      - mongo
    env_file:
      - .env  

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
  payload:


