version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    restart: always  
    environment:
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_PUBLIC_CMS_URL: ${PUBLIC_CMS_URL}
      PAYLOAD_PUBLIC_APP_URL: ${PUBLIC_APP_URL}
      PAYLOAD_PUBLIC_DRAFT_SECRET: ${PUBLIC_DRAFT_SECRET}
      REVALIDATION_KEY: ${REVALIDATION_KEY}
      DATABASE_URI: ${DATABASE_URI}
      PORT: 7500
      NODE_ENV: production
    volumes:
      - /home/node/app:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    networks:
      - proxy
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:

networks:
  proxy: 
    external: true  
